name: Sedex Website Monitor

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch: # 支持在 GitHub 页面手动点击按钮一键执行

jobs:
  build-and-send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 lxml

      - name: Run script and Send email
        # 把你之前在仓库里配置好的密码和服务器变量安全的传进 Python
        env:
          MAIL_SERVER: ${{ secrets.MAIL_SERVER }}
          MAIL_PORT: ${{ secrets.MAIL_PORT }}
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          MAIL_FROM: ${{ secrets.MAIL_FROM }}
        run: |
          python -u fetch_sedex.py
